import React, { useState, useEffect } from "react"
import type { NextPage } from "next"
import Head from "next/head"
import { useDispatch, useSelector, shallowEqual } from "react-redux"
import { useRouter } from "next/router"
import dynamic from "next/dynamic"

import "tiny-slider/dist/tiny-slider.css"

import { api } from "../../services/api"
import { useStoreDispatch, RootState } from "../../redux/store"
import { fetchProduct, reset } from "../../redux/product.slice"

import Layout from "../../layouts/Layout"

const ProductCarousel = dynamic(
  () => import("../../components/product/ProductCarousel"),
  { ssr: false },
)

const ProductDetails = dynamic(
  () => import("../../components/product/ProductDetails"),
  { ssr: false },
)

// import ProductDetails from "../../components/product/ProductDetails"
import ProductGallery from "../../components/product/ProductGallery"
import ProductReviews from "../../components/product/ProductReviews"

const Product: NextPage = () => {
  const router = useRouter()
  const { id } = router.query

  const dispatch = useStoreDispatch()
  const { Contents, Status } = useSelector((state: RootState) => state.product)
  const RelatedProducts = useSelector(
    (state: RootState) => state.product.RelatedProducts,
    shallowEqual,
  )

  useEffect(() => {
    if (!id) return
    dispatch(fetchProduct(id as string))

    return () => {
      dispatch(reset())
    }
  }, [dispatch, id])

  return (
    <Layout
      pageTitle={Contents?.Description || ""}
      loading={Status === "loading"}
    >
      <Head>
        <title>Baas Verpakkingen B.V.</title>
        <meta name="description" content="Generated by create bext app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <div className="bg-light shadow-lg rounded-3 px-4 py-3 mb-5">
          <div className="px-lg-3">
            <div className="row">
              <div className="col-lg-7 pe-lg-0 pt-lg-4">
                {Contents && Contents?.Images?.length > 0 && (
                  <ProductGallery images={Contents.Images} />
                )}
              </div>
              <div className="col-lg-5 pt-4 pt-lg-0">
                <ProductDetails />
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="border-top border-bottom my-lg-3 py-5">
        {Status === "done" && (
          <ProductReviews reviews={Contents?.Reviews || []} />
        )}
      </div>

      {RelatedProducts && RelatedProducts?.length > 0 && (
        <div className="container py-5 my-md-3">
          <h2 className="h3 text-center pb-4">GERELATEERDE PRODUCTEN</h2>
          <ProductCarousel products={RelatedProducts} />
        </div>
      )}
    </Layout>
  )
}

export default Product
